[[ClassifierRules]]
EnumerationScope = "DirectoryEnumeration"
RuleName = "DiscardLinuxSystemDirs"
MatchAction = "Discard"
Description = "File paths that will be skipped entirely."
MatchLocation = "FilePath"
WordListType = "StartsWith"
MatchLength = 0
WordList = [
"\\/bin",
"\\/boot",
"\\/dev",
"\\/proc",
"\\/run",
"\\/usr",
"\\/var",
"\\/sys",
]
Triage = "Green"
