from setuptools import setup, find_packages

setup(
    name="nessus_verifier",
    version="0.0.1",
    description="Pentests services from nessus file",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="kcancurly",
    url="https://github.com/kcancurly/nessus-verifier",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "argcomplete",
        "requests",
        "bs4",
        "dnspython",
        "impacket",
        "pyaml",
        "pysmb",
        "pymongo",
        "python-nmap",
        "rich",
        "psycopg",
        "paramiko",
        "toml",
        "stomp.py",
        "pymssql",
        "asyncssh[bcrypt]",
        "colorama",
        "pymysql",
        "packaging",
        "pika",
        "redis[hiredis]",
        "BAC0",
        "nvdlib",
        "cidr_man",
        "selenium",
        "html5lib",
        "argcomplete",
        "python-i18n",
        "paho-mqtt",
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    entry_points={
        "console_scripts": [
            "nv-parse=src.modules.nv_parse:main",
            "nv-solver=src.solvers.solver:main",
            "nv-nmap=src.modules.nv_nmap:main",
            "nv-nuclei=src.modules.nv_nuclei:main",
            "nv-nc=src.modules.nv_nc:main",
            "nv-service=src.services.nv_services:main",
            "nv-url=src.url.url:main",
            "nv-nessus=src.modules.nv_nessus:main",
            "nv-misc=src.modules.nv_misc:main",
        ],
    },
)
