from setuptools import setup, find_packages

setup(
    name="nessus_verifier",
    version="0.0.1",
    description="Pentests services from nessus file",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="kcancurly",
    url="https://github.com/kcancurly/nessus-verifier",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "argcomplete",
        "requests",
        "dnspython",
        "ntplib",
        "impacket",
        "pyaml",
        "pysmb",
        "pymongo",
        "python-nmap",
        "rich",
        "psycopg",
        "paramiko",
        "toml",
        "stomp.py",
        "pymssql",
        "asyncssh[bcrypt]",
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.12",
    entry_points={
        "console_scripts": [
            "nv-parse=src.modules.nv_parse:main",
            "nv-solver=src.solvers.solver:main",
            "nv-nmap=src.modules.nv_nmap:main",
            "nv-service=src.services.nv_services:main",
        ],
    },
)
