[[Rule]]
scope = "Directory"
name = "OSDirectoryDiscard"
action = "Discard"
category = []
relay = []
description = "File paths that will be skipped entirely."
matchLocation = "FilePath"
matchLength = 0
importance = ""
wordListType = "EndsWith"
wordList = [
"\\/manuals?",
]
triage = "gray"