[[Rule]]
scope = "File"
name = "JavaDiscardByFileExtension"
action = "Discard"
category = []
relay = []
description = "Skip any further scanning for files with these extensions."
matchLocation = "FileExtension"
matchLength = 0
importance = ""
wordListType = "Exact"
wordList = [
"\\.class",
"\\.jar",
]
triage = "gray"