[[Rule]]
scope = "File"
name = "ApplicationsFileDiscard"
action = "Discard"
category = []
relay = []
description = "Skip any further scanning for file with these names."
matchLocation = "FileName"
matchLength = 0
importance = ""
wordListType = "StartsWith"
wordList = [
"readme\\.",
"news\\.",
]
triage = "gray"