[[Rule]]
scope = "File"
name = "CommvaultFileDiscardFileName"
action = "Discard"
category = []
relay = []
description = "Skip any further scanning for files with these extensions."
matchLocation = "FileName"
matchLength = 0
importance = ""
wordListType = "Exact"
wordList = [
"DCTot\\.cvf",
"DCInc\\.cvf",
]
triage = "gray"