[[Rule]]
scope = "Content"
id = "d4"
name = "Generic content snaffle"
action = "Snaffle"
category = []
relay = []
description = "Pick these up."
matchLocation = "FileContentAsString"
matchLength = 0
importance = "1⭐"
wordListType = "Contains"
wordList = [
".*password.*",
"passwd",
"pass",
"pwd",
"credential",
"cred",
"(s|ş)ifre",
"parola",
"secret",
"token",
"key",
"auth",
]
triage = "green"

[[Rule]]
scope = "Content"
id = "d8"
name = "KeepCertRegexRed"
action = "Snaffle"
category = []
relay = []
description = "Private keys."
matchLocation = "FileContentAsString"
importance = "5⭐"
wordListType = "Regex"
matchLength = 0
wordList = ["-----BEGIN( RSA| OPENSSH| DSA| EC| PGP)? PRIVATE KEY( BLOCK)?-----"]
triage = "red"

[[Rule]]
scope = "Content"
id = "d10"
name = "KeepConfigRegexRed"
action = "Snaffle"
category = []
relay = []
description = "A description of what a rule does."
matchLocation = "FileContentAsString"
importance = "5⭐"
wordListType = "Regex"
matchLength = 0
wordList = ["NVRAM config last updated", 
"enable password \\.", 
"simple-bind authenticated encrypt",
"\\.getConnection\\(\\\"jdbc\\:",
"passwo?r?d\\s*=\\s*[\\'\\\"][^\\'\\\"]....",
"connectionstring",
]
triage = "red"


[[Rule]]
scope = "Content"
id = "d15"
name = "KeepCmdRegexRedDontIgnoreCase"
action = "Snaffle"
category = []
relay = []
description = "Commands that have cleartext password in them."
matchLocation = "FileContentAsString"
importance = "5⭐"
wordListType = "Regex"
dontignorecase = true
matchLength = 0
wordList = ["ldapsearch.*-w.*",
]
triage = "red"

[[Rule]]
scope = "Content"
id = "d15"
name = "KeepCmdRegex"
action = "Snaffle"
category = []
relay = []
description = "Commands that have cleartext password in them."
matchLocation = "FileContentAsString"
importance = "5⭐"
wordListType = "Regex"
dontignorecase = true
matchLength = 0
wordList = [
"mongo.*(-p|--password) \\S+",
"mongodb:\\/\\/\\S+:\\S+@",
".*:\\/\\/\\S+:\\S+@",
".*bind_password.*",
"curl.*-u \\S+:\\S+ .*",
".*querypassword.*",
".*sqldbpassword.*",
]
triage = "red"

[[Rule]]
scope = "Content"
id = "d16"
name = "ContentDatabasesRed"
action = "Snaffle"
category = []
relay = []
description = "Database related matches."
matchLocation = "FileContentAsString"
wordListType = "Regex"
importance = "5⭐"
matchLength = 0
wordList = [
"(mysql|mongodb|postgresql):\\/\\/\\S+:\\S+@",   # MYSQL, MONGODB, PSQL
]
triage = "red"

[[Rule]]
scope = "Content"
id = "d16"
name = "ContentDatabasesRedDIC"
action = "Snaffle"
category = []
relay = []
description = "Match SQL connection strings that appear to use integrated security (so no passwords)."
matchLocation = "FileContentAsString"
wordListType = "Contains"
importance = "5⭐"
matchLength = 0
dontignorecase = true
wordList = [
"IDENTIFIED BY",    # MYSQL SQL PASSWORD
"mysql.*(-p|--password)",   # MYSQL CLI
"couchbase-cli.*-p", # COUCHBASE
"mongo.*(-p|--password) \\S+",  # MONGODB
]
triage = "red"

[[Rule]]
scope = "Content"
id = "d16"
name = "ContentDatabasesRedDIC"
action = "Snaffle"
category = []
relay = []
description = "Match SQL connection strings that appear to use integrated security (so no passwords)."
matchLocation = "FileContentAsString"
wordListType = "Contains"
importance = "5⭐"
matchLength = 0
dontignorecase = true
wordList = [
"psql.*-w", # COUCHBASE
]
triage = "red"

[[Rule]]
scope = "Content"
id = "d16"
name = "ContentDatabasesYellow"
action = "Snaffle"
category = []
relay = []
description = "Match SQL connection strings that appear to use integrated security (so no passwords)."
matchLocation = "FileContentAsString"
wordListType = "Contains"
importance = "5⭐"
matchLength = 0
wordList = [
"couchbase-cli.*--config-path", # COUCHBASE
]
triage = "yellow"

[[Rule]]
scope = "Content"
id = "d16"
name = "KeepCSharpDbConnStringsYellow"
action = "Snaffle"
category = []
relay = []
description = "Match SQL connection strings that appear to use integrated security (so no passwords)."
matchLocation = "FileContentAsString"
wordListType = "Regex"
importance = "3⭐"
matchLength = 0
wordList = ["Data Source=.+Integrated Security=(SSPI|true)","Integrated Security=(SSPI|true);.*Data Source=.+"]
triage = "yellow"

[[Rule]]
scope = "Content"
id = "d17"
name = "KeepCSharpDbConnStringsRed"
action = "Snaffle"
category = []
relay = []
description = "Match SQL connection strings that appear to have a password."
matchLocation = "FileContentAsString"
importance = "5⭐"
wordListType = "Regex"
matchLength = 0
wordList = ["Data Source=.+(;|)Password=.+(;|)","Password=.+(;|)Data Source=.+(;|)"]  # ["(?!.+Integrated Security)Data Source=.+Password=.+"]
triage = "red"

[[Rule]]
scope = "Content"
id = "d18"
name = "KeepCSharpViewstateKeys"
action = "Snaffle"
category = []
relay = []
description = "Files with contents matching these regexen are very interesting."
matchLocation = "FileContentAsString"
importance = "5⭐"
wordListType = "Regex"
matchLength = 0
wordList = ["validationkey\\s*=\\s*[\\'\\\"][^\\'\\\"]....",
"decryptionkey\\s*=\\s*[\\'\\\"][^\\'\\\"]...."]
triage = "red" 

[[Rule]]
scope = "Content"
name = "Snaffler KeepRdpPasswords"
action = "Snaffle"
category = []
relay = []
description = "Files with contents matching these regexen are very interesting."
matchLocation = "FileContentAsString"
importance = "5⭐"
wordListType = "Regex"
matchLength = 0
wordList = ["password 51\\:b"]
triage = "red"

[[Rule]]
scope = "Content"
name = "Snaffler KeepFFRegexRed"
action = "Snaffle"
category = []
relay = []
description = "Files with contents matching these regexes are very interesting."
matchLocation = "FileContentAsString"
wordListType = "Regex"
matchLength = 0
importance = "5⭐"
wordList = ["\"encryptedPassword\":\"[A-Za-z0-9+/=]+\""]
triage = "red"

[[Rule]]
scope = "Content"
name = "Snaffler KeepUnattendXmlRegexRed"
action = "Snaffle"
category = []
relay = []
description = "Files with contents matching these regexen are very interesting."
matchLocation = "FileContentAsString"
wordListType = "Regex"
matchLength = 0
importance = "5⭐"
wordList = ["(?s)<AdministratorPassword>.{0,30}<Value>.*<\\/Value>",
"(?s)<AutoLogon>.{0,30}<Value>.*<\\/Value>"]
triage = "red"

[[Rule]]
scope = "Content"
name = "Snaffler KeepNetConfigCreds"
action = "Snaffle"
category = []
relay = []
description = "A description of what a rule does."
matchLocation = "FileContentAsString"
wordListType = "Regex"
matchLength = 0
importance = "5⭐"
wordList = ["NVRAM config last updated", 
"enable password \\.", 
"simple-bind authenticated encrypt",
"pac key [0-7] ",
"snmp-server community\\s.+\\sRW"]
triage = "red"

[[Rule]]
scope = "Content"
name = "Snaffler KeepPerlDbConnStrings"
action = "Snaffle"
category = []
relay = []
description = "Files with contents matching these regexen are very interesting."
matchLocation = "FileContentAsString"
wordListType = "Regex"
matchLength = 0
importance = "5⭐"
wordList = ["DBI\\-\\>connect\\("]
triage = "red"

[[Rule]]
scope = "Content"
name = "KeepPerlOracleConnStrings"
action = "Snaffle"
category = []
relay = []
description = "Files with contents matching these regexen are very interesting."
matchLocation = "FileContentAsString"
wordListType = "Regex"
matchLength = 0
importance = "5⭐"
wordList = [".*cx_oracle\\.connect.*"]
triage = "red"

[[Rule]]
scope = "Content"
name = "Snaffler KeepPsCredentials"
action = "Snaffle"
category = []
relay = []
description = "Files with contents matching these regexen are very interesting."
matchLocation = "FileContentAsString"
wordListType = "Regex"
matchLength = 0
importance = "5⭐"
wordList = [    "-SecureString",
"-AsPlainText",
"\\[Net.NetworkCredential\\]::new\\("]
triage = "red"

[[Rule]]
scope = "Content"
name = "Snaffler KeepPyDbConnStrings"
action = "Snaffle"
category = []
relay = []
description = "Files with contents matching these regexen are very interesting."
matchLocation = "FileContentAsString"
wordListType = "Regex"
matchLength = 0
importance = "5⭐"
wordList = ["mysql\\.connector\\.connect\\(",
"psycopg2\\.connect\\("]
triage = "red"

[[Rule]]
scope = "Content"
name = "Snaffler KeepRubyDbConnStrings"
action = "Snaffle"
category = []
relay = []
description = "Files with contents matching these regexen are very interesting."
matchLocation = "FileContentAsString"
wordListType = "Regex"
matchLength = 0
importance = "5⭐"
wordList = ["DBI\\.connect\\("]
triage = "red"

[[Rule]]
scope = "Content"
name = "Snaffler KeepAwsKeysInCode"
action = "Snaffle"
category = []
relay = []
description = "Files with contents matching these regexen are very interesting."
matchLocation = "FileContentAsString"
wordListType = "Regex"
matchLength = 0
importance = "5⭐"
wordList = ["aws[_\\-\\.]?key",
"(\\s|\\'|\\\"|\\^|=)(A3T[A-Z0-9]|AKIA|AGPA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z2-7]{12,16}(\\s|\\'|\\\"|$)"]
triage = "red"

[[Rule]]
scope = "Content"
name = "Snaffler KeepDbConnStringPw"
action = "Snaffle"
category = []
relay = []
description = "Files with contents matching these regexen are very interesting."
matchLocation = "FileContentAsString"
wordListType = "Regex"
matchLength = 0
importance = "3⭐"
wordList = ["connectionstring.{1,200}passw"]
triage = "yellow"

[[Rule]]
scope = "Content"
name = "Snaffler KeepPassOrKeyInCode"
action = "Snaffle"
category = []
relay = []
description = "Files with contents matching these regexen are very interesting."
matchLocation = "FileContentAsString"
wordListType = "Regex"
matchLength = 0
importance = "5⭐"
wordList = ["passw?o?r?d\\s*=\\s*[\\'\\\"][^\\'\\\"]....",
"api[Kk]ey\\s*=\\s*[\\'\\\"][^\\'\\\"]....",
"passw?o?r?d?>\\s*[^\\s<]+\\s*<",
"passw?o?r?d?>.{3,2000}</pass",
"[\\s]+-passw?o?r?d?",
"api[kK]ey>\\s*[^\\s<]+\\s*<",
"[_\\-\\.]oauth\\s*=\\s*[\\'\\\"][^\\'\\\"]....",
"client_secret\\s*=*\\s*",
"<ExtendedMatchKey>ClientAuth",
"GIUserPassword"
]
triage = "red"

[[Rule]]
scope = "Content"
name = "Snaffler KeepS3UriPrefixInCode"
action = "Snaffle"
category = []
relay = []
description = "Files with content matching an AWS S3 or Apache Hadoop S3A URI Prefix"
matchLocation = "FileContentAsString"
wordListType = "Regex"
matchLength = 0
importance = "3⭐"
wordList = ["s3[a]?:\\/\\/[a-zA-Z0-9\\-\\+\\/]{2,16}"]
triage = "yellow"

[[Rule]]
scope = "Content"
name = "Snaffler KeepSlackTokensInCode"
action = "Snaffle"
category = []
relay = []
description = "Files with contents matching these regexen are very interesting."
matchLocation = "FileContentAsString"
wordListType = "Regex"
matchLength = 0
importance = "5⭐"
wordList = ["(xox[pboa]-[0-9]{12}-[0-9]{12}-[0-9]{12}-[a-z0-9]{32})",
"https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}"]
triage = "red"

[[Rule]]
scope = "Content"
name = "Snaffler KeepSqlAccountCreation"
action = "Snaffle"
category = []
relay = []
description = "Files with contents matching these regexen are very interesting."
matchLocation = "FileContentAsString"
wordListType = "Regex"
matchLength = 0
importance = "5⭐"
wordList = ["CREATE (USER|LOGIN) .{0,200} (IDENTIFIED BY|WITH PASSWORD)"]
triage = "red"

[[Rule]]
scope = "Content"
name = "KeytoolRegexRed"
action = "Snaffle"
category = []
relay = []
description = "Keytool pass commands."
matchLocation = "FileContentAsString"
importance = "5⭐"
wordListType = "Regex"
dontignorecase = true
matchLength = 0
wordList = ["keytool.*-srcstorepass.*",
"keytool.*-keypass",
"keytool.*-srckeypass",
"keytool.*-destkeypass",
"keytool.*-deststorepass",
]
triage = "red"