[[Rule]]
scope = "Content"
id = "d4"
name = "Generic content snaffle"
action = "Snaffle"
category = []
relay = []
description = "Pick these up."
matchLocation = "FileContentAsString"
matchLength = 0
importance = "⭐"
wordListType = "Contains"
wordList = [
"password",
"passwd",
"pass",
"pwd",
"credential",
"cred",
"sifre",
"şifre",
"secret",
]
triage = "green"

[[Rule]]
scope = "Content"
id = "d8"
name = "KeepCertRegexRed"
action = "Snaffle"
category = []
relay = []
description = "Private keys."
matchLocation = "FileContentAsString"
importance = "⭐⭐⭐⭐⭐"
wordListType = "Regex"
matchLength = 0
wordList = ["-----BEGIN( RSA| OPENSSH| DSA| EC| PGP)? PRIVATE KEY( BLOCK)?-----"]
triage = "red"

[[Rule]]
scope = "Content"
id = "d10"
name = "KeepConfigRegexRed"
action = "Snaffle"
category = []
relay = []
description = "A description of what a rule does."
matchLocation = "FileContentAsString"
importance = "⭐⭐⭐⭐⭐"
wordListType = "Regex"
matchLength = 0
wordList = ["NVRAM config last updated", 
"enable password \\.", 
"simple-bind authenticated encrypt",
"\\.getConnection\\(\\\"jdbc\\:",
"passwo?r?d\\s*=\\s*[\\'\\\"][^\\'\\\"]....",
"connectionstring",
]
triage = "red"

[[Rule]]
scope = "File"
id = "d13"
name = "KeepFilenameExactYellow"
action = "Snaffle"
category = []
relay = []
description = "Files with these exact names are very interesting."
matchLocation = "FileName"
importance = "⭐⭐⭐"
wordListType = "EndsWith"
matchLength = 0
wordList = [
"web\\.config", 
"\\.bash_history",
"\\.zsh_history",
]
triage = "yellow"

[[Rule]]
scope = "File"
id = "d14"
name = "KeepNameContainsGreen"
action = "Snaffle"
category = []
relay = []
description = "A description of what a rule does."
matchLocation = "FileName"
importance = "⭐"
wordListType = "Contains"
matchLength = 0
wordList = ["passw",
"secret",
"credential",
"thycotic",
"cyberark"]
triage = "green"

[[Rule]]
scope = "Content"
id = "d15"
name = "KeepCmdRegexRedDontIgnoreCase"
action = "Snaffle"
category = []
relay = []
description = "Commands that have cleartext password in them."
matchLocation = "FileContentAsString"
importance = "⭐⭐⭐⭐⭐"
wordListType = "Regex"
dontignorecase = true
matchLength = 0
wordList = ["ldapsearch.*-w.*", 
]
triage = "red"

[[Rule]]
scope = "Content"
id = "d16"
name = "KeepCSharpDbConnStringsYellow"
action = "Snaffle"
category = []
relay = []
description = "Match SQL connection strings that appear to use integrated security (so no passwords)."
matchLocation = "FileContentAsString"
wordListType = "Regex"
importance = "⭐⭐⭐"
matchLength = 0
wordList = ["Data Source=.+Integrated Security=(SSPI|true)","Integrated Security=(SSPI|true);.*Data Source=.+"]
triage = "yellow"

[[Rule]]
scope = "Content"
id = "d17"
name = "KeepCSharpDbConnStringsRed"
action = "Snaffle"
category = []
relay = []
description = "Match SQL connection strings that appear to have a password."
matchLocation = "FileContentAsString"
importance = "⭐⭐⭐⭐⭐"
wordListType = "Regex"
matchLength = 0
wordList = ["Data Source=.+(;|)Password=.+(;|)","Password=.+(;|)Data Source=.+(;|)"]  # ["(?!.+Integrated Security)Data Source=.+Password=.+"]
triage = "red"

[[Rule]]
scope = "Content"
id = "d18"
name = "KeepCSharpViewstateKeys"
action = "Snaffle"
category = []
relay = []
description = "Files with contents matching these regexen are very interesting."
matchLocation = "FileContentAsString"
importance = "⭐⭐⭐⭐⭐"
wordListType = "Regex"
matchLength = 0
wordList = ["validationkey\\s*=\\s*[\\'\\\"][^\\'\\\"]....",
"decryptionkey\\s*=\\s*[\\'\\\"][^\\'\\\"]...."]
triage = "red" 

[[Rule]]
scope = "Content"
name = "Snaffler KeepRdpPasswords"
action = "Snaffle"
category = []
relay = []
description = "Files with contents matching these regexen are very interesting."
matchLocation = "FileContentAsString"
importance = "⭐⭐⭐⭐⭐"
wordListType = "Regex"
matchLength = 0
wordList = ["password 51\\:b"]
triage = "red"