[[Rule]]
scope = "File"
name = "Firefox"
action = "Snaffle"
category = []
relay = []
description = "Pick these up."
matchLocation = "FileName"
matchLength = 0
importance = "⭐⭐"
wordListType = "EndsWith"
wordList = [
"\\.mozilla\\/firefox\\/.*/logins\\.json",
]
triage = "blue"

[[Rule]]
scope = "File"
name = "Generic Config File"
action = "Snaffle"
category = []
relay = []
description = "Pick these up."
matchLocation = "FileName"
matchLength = 0
importance = "⭐⭐"
wordListType = "EndsWith"
wordList = [
"\\.conf",
"\\.config",
"web\\.config", 
]
triage = "blue"

[[Rule]]
scope = "File"
id = "d9"
name = "Snaffler KeepPathContainsRed"
action = "Snaffle"
category = []
relay = []
description = "Files with a path containing these strings are very interesting."
matchLocation = "FilePath"
importance = "⭐⭐⭐⭐⭐"
wordListType = "Contains"
matchLength = 0
wordList = ["\\.purple\\/accounts.xml", 
"\\.gem\\/credentials", 
"config\\/hub"]
triage = "red"

[[Rule]]
scope = "File"
id = "d11"
name = "Snaffler KeepExtExactYellow"
action = "Snaffle"
category = []
relay = []
description = "Files with these extensions are a little interesting."
matchLocation = "FileExtension"
importance = "⭐⭐⭐"
wordListType = "Exact"
matchLength = 0
wordList = ["\\.key", 
"\\.keypair", 
"\\.jks", ]
triage = "yellow"

[[Rule]]
scope = "File"
id = "d12"
name = "Snaffler KeepFilenameExactRed"
action = "Snaffle"
category = []
relay = []
description = "Files with these exact names are very interesting."
matchLocation = "FilePath"
importance = "⭐⭐⭐⭐⭐"
wordListType = "EndsWith"
matchLength = 0
wordList = [
"otr\\.private_key", 
"Favorites\\.plist", 
"proxy\\.config", 
"keystore", 
"keyring", 
"\\.gitconfig", 
"\\.dockercfg", 
"key3\\.db", 
"key4\\.db", 
"Login Data",
"\\.htpasswd",
"accounts\\.v4"
]
triage = "red"

[[Rule]]
scope = "File"
name = "Snaffler KeepSSHKeysByFileName"
action = "Snaffle"
category = []
relay = []
description = "SSHKeys"
matchLocation = "FileName"
wordListType = "Exact"
matchLength = 0
importance = "⭐⭐⭐⭐"
wordList = ["id_rsa",
"id_dsa",
"id_ecdsa",
"id_ed25519",
]
triage = "orange1"

[[Rule]]
scope = "File"
name = "Snaffler KeepSSHKeysByFilExtension"
action = "Snaffle"
category = []
relay = []
description = "SSHKeys"
matchLocation = "FileExtension"
wordListType = "EndsWith"
matchLength = 0
importance = "⭐⭐⭐⭐"
wordList = ["\\.ppk",
]
triage = "orange1"

[[Rule]]
scope = "File"
name = "Snaffler KeepFtpClientConfigConfigByName"
action = "Snaffle"
category = []
relay = []
description = "Files with these exact names are very interesting."
matchLocation = "FileName"
wordListType = "Exact"
matchLength = 0
importance = "⭐⭐⭐⭐⭐"
wordList = ["recentservers\\.xml",
"sftp-config\\.json"]
triage = "red"

[[Rule]]
scope = "File"
name = "Snaffler KeepRemoteAccessConfByExtension"
action = "Snaffle"
category = []
relay = []
description = "Files with these extensions are a little interesting."
matchLocation = "FileExtension"
wordListType = "Exact"
matchLength = 0
importance = "⭐⭐⭐"
wordList = ["\\.rdg","\\.rtsz","\\.rtsx","\\.ovpn","\\.tvopt","\\.sdtid"]
triage = "yellow"

[[Rule]]
scope = "File"
name = "Snaffler KeepRemoteAccessConfByName"
action = "Snaffle"
description = "Files with these exact names are very very interesting."
matchLocation = "FileName"
wordListType = "Exact"
matchLength = 0
importance = "⭐⭐⭐⭐⭐"
wordList = [ "mobaxterm\\.ini",
"mobaxterm backup\\.zip",
"confCons.xml"]
triage = "red"

[[Rule]]
scope = "File"
name = "Snaffler KeepPassMgrsByExtension"
action = "Snaffle"
category = []
relay = []
description = "Files with these extensions are very very interesting."
matchLocation = "FileExtension"
wordListType = "Exact"
matchLength = 0
importance = "⭐⭐⭐⭐⭐"
wordList = ["\\.kdbx",
"\\.kdb",
"\\.psafe3",
"\\.kwallet",
"\\.keychain",
"\\.agilekeychain",
"\\.cred"]
triage = "red"

[[Rule]]
scope = "File"
name = "Snaffler KeepPasswordFilesByName"
action = "Snaffle"
category = []
relay = []
description = "Files with these exact names are very interesting."
matchLocation = "FileName"
wordListType = "Exact"
matchLength = 0
importance = "⭐⭐⭐⭐⭐"
wordList = ["passwords\\.txt",
"pass\\.txt",
"accounts\\.txt",
"passwords\\.doc",
"pass\\.doc",
"accounts\\.doc",
"passwords\\.xls",
"pass\\.xls",
"accounts\\.xls",
"passwords\\.docx",
"pass\\.docx",
"accounts\\.docx",
"passwords\\.xlsx",
"pass\\.xlsx",
"accounts\\.xlsx",
"secrets\\.txt",
"secrets\\.doc",
"secrets\\.xls",
"secrets\\.docx",
"BitlockerLAPSPasswords\\.csv",
"secrets\\.xlsx"]
triage = "red"

[[Rule]]
scope = "File"
name = "Snaffler KeepGitCredsByName"
action = "Snaffle"
category = []
relay = []
description = "Files with these exact names are very interesting."
matchLocation = "FileName"
wordListType = "Exact"
matchLength = 0
importance = "⭐⭐⭐⭐⭐"
wordList = ["\\.git-credentials"]
triage = "red"

[[Rule]]
scope = "File"
name = "Snaffler KeepShellHistoryByName"
action = "Snaffle"
category = []
relay = []
description = "Files with these exact names are very interesting."
matchLocation = "FileName"
wordListType = "Exact"
matchLength = 0
importance = "⭐⭐"
wordList = ["\\.bash_history",
"\\.zsh_history",
"\\.sh_history",
"zhistory",
"\\.irb_history",
"ConsoleHost_History\\.txt"]
triage = "blue"

[[Rule]]
scope = "File"
name = "Snaffler KeepShellRcFilesByName"
action = "Snaffle"
category = []
relay = []
description = "Files with these exact names are very interesting."
matchLocation = "FileName"
wordListType = "Exact"
matchLength = 0
wordList = ["\\.netrc",
"_netrc",
"\\.exports",
"\\.functions",
"\\.extra",
"\\.npmrc",
"\\.env",
"\\.bashrc",
"\\.profile",
"\\.zshrc"]
triage = "green"

[[Rule]]
scope = "File"
name = "Snaffler KeepDbMgtConfigByName"
action = "Snaffle"
category = []
relay = []
description = "Files with these exact names are very interesting."
matchLocation = "FileName"
wordListType = "Exact"
matchLength = 0
wordList = ["SqlStudio\\.bin",
"\\.mysql_history",
"\\.psql_history",
"\\.pgpass",
"\\.dbeaver-data-sources\\.xml",
"credentials-config\\.json",
"dbvis\\.xml",
"robomongo\\.json"]
triage = "red"