[[Rule]]
scope = "File"
name = "Firefox"
action = "Snaffle"
category = []
relay = []
description = "Pick these up."
matchLocation = "FileName"
matchLength = 0
importance = "2⭐"
wordListType = "EndsWith"
wordList = [
"\\.mozilla\\/firefox\\/.*/logins\\.json",
]
triage = "blue"

[[Rule]]
scope = "File"
name = "Generic Config File"
action = "Snaffle"
category = []
relay = []
description = "Pick these up."
matchLocation = "FileName"
matchLength = 0
importance = "2⭐"
wordListType = "EndsWith"
wordList = [
"\\.conf",
"\\.config",
"web\\.config", 
]
triage = "blue"

[[Rule]]
scope = "File"
id = "d9"
name = "Snaffler KeepPathContainsRed"
action = "Snaffle"
category = []
relay = []
description = "Files with a path containing these strings are very interesting."
matchLocation = "FilePath"
importance = "5⭐"
wordListType = "Contains"
matchLength = 0
wordList = ["\\.purple\\/accounts.xml", 
"\\.gem\\/credentials", 
"config\\/hub"]
triage = "red"

[[Rule]]
scope = "File"
id = "d11"
name = "Snaffler KeepExtExactYellow"
action = "Snaffle"
category = []
relay = []
description = "Files with these extensions are a little interesting."
matchLocation = "FileExtension"
importance = "3⭐"
wordListType = "Exact"
matchLength = 0
wordList = ["\\.key", 
"\\.keypair", 
"\\.jks", ]
triage = "yellow"

[[Rule]]
scope = "File"
id = "d12"
name = "Snaffler KeepFilenameExactRed"
action = "Snaffle"
category = []
relay = []
description = "Files with these exact names are very interesting."
matchLocation = "FilePath"
importance = "5⭐"
wordListType = "EndsWith"
matchLength = 0
wordList = [
"otr\\.private_key", 
"Favorites\\.plist", 
"proxy\\.config", 
"keystore", 
"keyring", 
"\\.gitconfig", 
"\\.dockercfg", 
"key3\\.db", 
"key4\\.db", 
"Login Data",
"\\.htpasswd",
"accounts\\.v4"
]
triage = "red"

[[Rule]]
scope = "File"
name = "Snaffler KeepSSHKeysByFileName"
action = "Snaffle"
category = []
relay = []
description = "SSHKeys"
matchLocation = "FileName"
wordListType = "Exact"
matchLength = 0
importance = "4⭐"
wordList = ["id_rsa",
"id_dsa",
"id_ecdsa",
"id_ed25519",
]
triage = "orange1"

[[Rule]]
scope = "File"
name = "Snaffler KeepSSHKeysByFilExtension"
action = "Snaffle"
category = []
relay = []
description = "SSHKeys"
matchLocation = "FileExtension"
wordListType = "EndsWith"
matchLength = 0
importance = "4⭐"
wordList = ["\\.ppk",
]
triage = "orange1"

[[Rule]]
scope = "File"
name = "Snaffler KeepFtpClientConfigConfigByName"
action = "Snaffle"
category = []
relay = []
description = "Files with these exact names are very interesting."
matchLocation = "FileName"
wordListType = "Exact"
matchLength = 0
importance = "5⭐"
wordList = ["recentservers\\.xml",
"sftp-config\\.json"]
triage = "red"

[[Rule]]
scope = "File"
name = "Snaffler KeepRemoteAccessConfByExtension"
action = "Snaffle"
category = []
relay = []
description = "Files with these extensions are a little interesting."
matchLocation = "FileExtension"
wordListType = "Exact"
matchLength = 0
importance = "3⭐"
wordList = ["\\.rdg","\\.rtsz","\\.rtsx","\\.ovpn","\\.tvopt","\\.sdtid"]
triage = "yellow"

[[Rule]]
scope = "File"
name = "Snaffler KeepRemoteAccessConfByName"
action = "Snaffle"
description = "Files with these exact names are very very interesting."
matchLocation = "FileName"
wordListType = "Exact"
matchLength = 0
importance = "5⭐"
wordList = [ "mobaxterm\\.ini",
"mobaxterm backup\\.zip",
"confCons.xml"]
triage = "red"

[[Rule]]
scope = "File"
name = "Snaffler KeepPassMgrsByExtension"
action = "Snaffle"
category = []
relay = []
description = "Files with these extensions are very very interesting."
matchLocation = "FileExtension"
wordListType = "Exact"
matchLength = 0
importance = "5⭐"
wordList = ["\\.kdbx",
"\\.kdb",
"\\.psafe3",
"\\.kwallet",
"\\.keychain",
"\\.agilekeychain",
"\\.cred"]
triage = "red"

[[Rule]]
scope = "File"
name = "Snaffler KeepPasswordFilesByName"
action = "Snaffle"
category = []
relay = []
description = "Files with these exact names are very interesting."
matchLocation = "FileName"
wordListType = "Exact"
matchLength = 0
importance = "5⭐"
wordList = ["passwords\\.txt",
"pass\\.txt",
"accounts\\.txt",
"passwords\\.doc",
"pass\\.doc",
"accounts\\.doc",
"passwords\\.xls",
"pass\\.xls",
"accounts\\.xls",
"passwords\\.docx",
"pass\\.docx",
"accounts\\.docx",
"passwords\\.xlsx",
"pass\\.xlsx",
"accounts\\.xlsx",
"secrets\\.txt",
"secrets\\.doc",
"secrets\\.xls",
"secrets\\.docx",
"BitlockerLAPSPasswords\\.csv",
"secrets\\.xlsx"]
triage = "red"

[[Rule]]
scope = "File"
name = "Snaffler KeepGitCredsByName"
action = "Snaffle"
category = []
relay = []
description = "Files with these exact names are very interesting."
matchLocation = "FileName"
wordListType = "Exact"
matchLength = 0
importance = "5⭐"
wordList = ["\\.git-credentials"]
triage = "red"

[[Rule]]
scope = "File"
name = "Snaffler KeepShellHistoryByName"
action = "Snaffle"
category = []
relay = []
description = "Files with these exact names are very interesting."
matchLocation = "FileName"
wordListType = "Exact"
matchLength = 0
importance = "2⭐"
wordList = ["\\.bash_history",
"\\.zsh_history",
"\\.sh_history",
"zhistory",
"\\.irb_history",
"ConsoleHost_History\\.txt"]
triage = "blue"

[[Rule]]
scope = "File"
name = "Snaffler KeepShellRcFilesByName"
action = "Snaffle"
category = []
relay = []
description = "Files with these exact names are very interesting."
matchLocation = "FileName"
wordListType = "Exact"
matchLength = 0
importance = "⭐"
wordList = ["\\.netrc",
"_netrc",
"\\.exports",
"\\.functions",
"\\.extra",
"\\.npmrc",
"\\.env",
"\\.bashrc",
"\\.profile",
"\\.zshrc"]
triage = "green"

[[Rule]]
scope = "File"
name = "Snaffler KeepDbMgtConfigByName"
action = "Snaffle"
category = []
relay = []
description = "Files with these exact names are very interesting."
matchLocation = "FileName"
wordListType = "Exact"
matchLength = 0
importance = "5⭐"
wordList = ["SqlStudio\\.bin",
"\\.mysql_history",
"\\.psql_history",
"\\.pgpass",
"\\.dbeaver-data-sources\\.xml",
"credentials-config\\.json",
"dbvis\\.xml",
"robomongo\\.json"]
triage = "red"

[[Rule]]
scope = "File"
name = "Snaffler KeepCloudApiKeysByName"
action = "Snaffle"
category = []
relay = []
description = "Files with these exact names are very interesting."
matchLocation = "FileName"
wordListType = "Exact"
matchLength = 0
importance = "5⭐"
wordList = ["\\.tugboat"]
triage = "red"

[[Rule]]
scope = "File"
name = "Snaffler KeepCloudApiKeysByPath"
action = "Snaffle"
category = []
relay = []
description = "Files with a path containing these strings are very very interesting."
matchLocation = "FilePath"
wordListType = "Contains"
matchLength = 0
importance = "5⭐"
wordList = ["\\/.aws\\/",
"doctl\\/config.yaml"]
triage = "red"

[[Rule]]
scope = "File"
name = "Snaffler KeepJenkinsByName"
action = "Snaffle"
category = []
relay = []
description = "Files with these exact names are very interesting."
matchLocation = "FileName"
wordListType = "Exact"
matchLength = 0
importance = "5⭐"
wordList = ["jenkins\\.plugins\\.publish_over_ssh\\.BapSshPublisherPlugin\\.xml",
"credentials\\.xml"]
triage = "red"

[[Rule]]
scope = "File"
name = "Snaffler KeepDatabaseByExtension"
action = "Snaffle"
category = []
relay = []
description = "Files with these extensions are a little interesting."
matchLocation = "FileExtension"
wordListType = "Exact"
matchLength = 0
importance = "3⭐"
wordList = [
"\\.mdf",
"\\.sdf",
"\\.sqldump",
"\\.bak"]
triage = "yellow"

[[Rule]]
scope = "File"
name = "Snaffler KeepDefenderConfigByName"
action = "Snaffle"
category = []
relay = []
description = "Files containing Defender Configs are very interesting."
matchLocation = "FileName"
wordListType = "Exact"
matchLength = 0
importance = "3⭐"
wordList = ["SensorConfiguration.json","mdatp_managed.json"]
triage = "yellow"

[[Rule]]
scope = "File"
name = "Snaffler KeepDeployImageByExtension"
action = "Snaffle"
category = []
relay = []
description = "Files with these extensions are a little interesting."
matchLocation = "FileExtension"
wordListType = "Exact"
matchLength = 0
importance = "3⭐"
wordList = [
"\\.wim",
"\\.ova",
"\\.ovf"]
triage = "yellow"

[[Rule]]
scope = "File"
name = "Snaffler KeepDomainJoinCredsByName"
action = "Snaffle"
category = []
relay = []
description = "Files containing Domain Join Credes are quite interesting."
matchLocation = "FileName"
wordListType = "Exact"
matchLength = 0
importance = "3⭐"
wordList = ["customsettings.ini"]
triage = "yellow"

[[Rule]]
scope = "File"
name = "Snaffler KeepDomainJoinCredsByPath"
action = "Snaffle"
category = []
relay = []
description = "Files with a path containing these strings are very interesting."
matchLocation = "FilePath"
wordListType = "Contains"
matchLength = 0
importance = "5⭐"
wordList = ["control\\\\customsettings.ini"]
triage = "red"

[[Rule]]
scope = "File"
name = "Snaffler KeepSCCMBootVarCredsByPath"
action = "Snaffle"
category = []
relay = []
description = "Files with a path containing these strings are very interesting."
matchLocation = "FilePath"
wordListType = "Regex"
matchLength = 0
importance = "5⭐"
wordList = ["REMINST\\\\SMSTemp\\\\.*\\.var",
			"SMS\\\\data\\\\Variables.dat",
			"SMS\\\\data\\\\Policy.xml"
		]
triage = "red"

[[Rule]]
scope = "File"
name = "Snaffler KeepUnattendXml"
action = "Snaffle"
category = []
relay = []
description = "Look inside unattend.xml files for actual values."
matchLocation = "FileName"
wordListType = "Exact"
matchLength = 0
importance = "⭐"
wordList = ["unattend\\.xml",
"Autounattend\\.xml"]
triage = "green"

[[Rule]]
scope = "File"
name = "Snaffler KeepFtpServerConfigByName"
action = "Snaffle"
category = []
relay = []
description = "Files with these exact names are very interesting."
matchLocation = "FileName"
wordListType = "Exact"
matchLength = 0
importance = "5⭐"
wordList = ["proftpdpasswd",
"filezilla\\.xml"]
triage = "red"

[[Rule]]
scope = "File"
name = "Snaffler KeepInfraAsCodeByExtension"
action = "Snaffle"
category = []
relay = []
description = "Files with these extensions are very very interesting."
matchLocation = "FileExtension"
wordListType = "Exact"
matchLength = 0
importance = "5⭐"
wordList = [    "\\.cscfg",
"\\.tfvars"]
triage = "red"

[[Rule]]
scope = "File"
name = "Snaffler KeepMemDumpByExtension"
action = "Snaffle"
category = []
relay = []
description = "Files with these extensions are a little interesting."
matchLocation = "FileExtension"
wordListType = "Exact"
matchLength = 0
importance = "5⭐"
wordList = ["\\.dmp"]
triage = "red"

[[Rule]]
scope = "File"
name = "Snaffler KeepMemDumpByName"
action = "Snaffle"
category = []
relay = []
description = "Files with these exact names are very very interesting."
matchLocation = "FileName"
wordListType = "Exact"
matchLength = 0
importance = "5⭐"
wordList = [ "MEMORY\\.DMP",
"hiberfil\\.sys",
"lsass\\.dmp",
"lsass\\.exe\\.dmp",]
triage = "red"

[[Rule]]
scope = "File"
name = "Snaffler KeepNetConfigFileByName"
action = "Snaffle"
category = []
relay = []
description = "Files with these exact names are very very interesting."
matchLocation = "FileName"
wordListType = "Exact"
matchLength = 0
importance = "5⭐"
wordList = [ "running-config\\.cfg",
"startup-config\\.cfg",
"running-config",
"startup-config"]
triage = "red"

[[Rule]]
scope = "File"
name = "Snaffler KeepKerberosCredentialsByExtension"
action = "Snaffle"
category = []
relay = []
description = "Files with these extensions are interesting."
matchLocation = "FileExtension"
wordListType = "Exact"
matchLength = 0
importance = "3⭐"
wordList = [
"\\.keytab",
"\\.CCACHE"]
triage = "yellow"

[[Rule]]
scope = "File"
name = "Snaffler KeepKerberosCredentialsByName"
action = "Snaffle"
category = []
relay = []
Ddescription = "Files with these names are interesting."
matchLocation = "FileName"
wordListType = "Regex"
matchLength = 0
importance = "3⭐"
wordList = [
"krb5cc_.*"]
triage = "yellow"

[[Rule]]
scope = "File"
name = "Snaffler KeepNixLocalHashesByName"
action = "Snaffle"
category = []
relay = []
description = "Files with these exact names are very very interesting."
matchLocation = "FileName"
wordListType = "Exact"
matchLength = 0
importance = "5⭐"
wordList = [ "shadow",
"pwd\\.db",
"passwd"]
triage = "red"

[[Rule]]
scope = "File"
name = "Snaffler KeepCyberArkConfigsByName"
action = "Snaffle"
category = []
relay = []
description = "Files with these exact names are very very interesting."
matchLocation = "FileName"
wordListType = "Exact"
matchLength = 0
importance = "5⭐"
wordList = [ 
	"Psmapp\\.cred",
	"psmgw\\.cred",
	"backup\\.key",
	"MasterReplicationUser\\.pass",
	"RecPrv\\.key",
	"ReplicationUser\\.pass",
	"Server\\.key",
	"VaultEmergency\\.pass",
	"VaultUser\\.pass",
	"Vault\\.ini",
	"PADR\\.ini",
	"PARAgent\\.ini",
	"CACPMScanner\\.exe\\.config",
	"PVConfiguration\\.xml"
	]
triage = "red"

[[Rule]]
scope = "File"
name = "Snaffler KeepPcapByExtension"
action = "Snaffle"
category = []
relay = []
description = "Files with these extensions are a little interesting."
matchLocation = "FileExtension"
wordListType = "Exact"
matchLength = 0
importance = "3⭐"
wordList = ["\\.pcap",
"\\.cap",
"\\.pcapng",
]
triage = "yellow"

[[Rule]]
scope = "File"
name = "Snaffler KeepWinHashesByName"
action = "Snaffle"
category = []
relay = []
description = "Files with these exact names are very very interesting."
matchLocation = "FileName"
wordListType = "Exact"
matchLength = 0
importance = "5⭐"
wordList = [ "NTDS.DIT",
"SYSTEM",
"SAM",
"SECURITY"]
triage = "red"

[[Rule]]
scope = "File"
name = "Snaffler KeepPhpByName"
action = "Snaffle"
category = []
relay = []
description = "Files with these exact names are very interesting."
matchLocation = "FileName"
wordListType = "Exact"
matchLength = 0
importance = "5⭐"
wordList = ["LocalSettings\\.php"]
triage = "red"

[[Rule]]
scope = "File"
name = "Snaffler KeepRubyByName"
action = "Snaffle"
category = []
relay = []
description = "Files with these exact names are very interesting."
matchLocation = "FileName"
wordListType = "Exact"
matchLength = 0
importance = "5⭐"
wordList = ["database\\.yml",
"\\.secret_token\\.rb",
"knife\\.rb",
"carrierwave\\.rb",
"omniauth\\.rb"]
triage = "red"

[[Rule]]
scope = "File"
id = "d14"
name = "KeepNameContainsGreen"
action = "Snaffle"
category = []
relay = []
description = "A description of what a rule does."
matchLocation = "FileName"
importance = "⭐"
wordListType = "Contains"
matchLength = 0
wordList = ["passw",
"secret",
"credential",
"thycotic",
"cyberark"]
triage = "green"