[[Rule]]
scope = "Directory"
id = "d1"
name = "DiscardLinuxSystemDirs"
action = "Discard"
category = []
relay = []
description = "File paths that will be skipped entirely."
matchLocation = "FilePath"
matchLength = 0
wordListType = "StartsWith"
wordList = [
"/bin",
"/boot",
"/dev",
"/etc",
"/lib",
"/lib64",
"/proc",
"/run",
"/usr",
"/var",
"/sbin",
"/sys",
"/opt",
]
triage = "Green"

[[Rule]]
scope = "File"
id = "d2"
name = "DiscardByFileExtension"
action = "Discard"
category = []
relay = []
description = "Skip any further scanning for files with these extensions."
matchLocation = "FilePath"
matchLength = 0
wordListType = "EndsWith"
wordList = [
".bmp",
".eps",
".gif",
".ico",
".jfi",
".jfif",
".jif",
".jpe",
".jpeg",
".jpg",
".png",
".psd",
".svg",
".tif",
".tiff",
".webp",
".xcf",
".ttf",
".otf",
".lock",
".css",
".less",
".admx",
".adml",
".xsd",
".nse",
".xsl",
".zip",
".tar",
".tar.gz",
".so",
]
triage = "Green"

[[Rule]]
scope = "File"
id = "d3"
name = "DiscardByFileName"
action = "Discard"
category = []
relay = []
description = "Skip any further scanning for files with these extensions."
matchLocation = "FilePath"
matchLength = 0
wordListType = "EndsWith"
wordList = [
"initrd.img",
"initrd.img.old",
]
triage = "Green"

[[Rule]]
scope = "Content"
id = "d4"
name = "Generic file content snaffle"
action = "Snaffle"
category = []
relay = []
description = "Pick these up."
matchLocation = "FileContentAsString"
matchLength = 0
wordListType = "Contains"
wordList = [
"password",
"passwd",
"pass",
]
triage = "Green"

[[Rule]]
scope = "File"
id = "d5"
name = "Interesting File"
action = "Snaffle"
category = []
relay = []
description = "Pick these up."
matchLocation = "FileName"
matchLength = 0
wordListType = "EndsWith"
wordList = [
".mozilla/firefox/.*/logins.json",
]
triage = "Green"