[[Rule]]
scope = "Directory"
id = "d1"
name = "DiscardLinuxSystemDirs"
action = "Discard"
category = []
relay = []
description = "File paths that will be skipped entirely."
matchLocation = "FilePath"
matchLength = 0
importance = ""
wordListType = "StartsWith"
wordList = [
"/bin",
"/boot",
"/dev",
"/etc",
"/lib",
"/lib64",
"/proc",
"/run",
"/usr",
"/var",
"/sbin",
"/sys",
"/opt",
]
triage = "gray"

[[Rule]]
scope = "File"
id = "d2"
name = "DiscardByFileExtension"
action = "Discard"
category = []
relay = []
description = "Skip any further scanning for files with these extensions."
matchLocation = "FilePath"
matchLength = 0
importance = ""
wordListType = "EndsWith"
wordList = [
".bmp",
".eps",
".gif",
".ico",
".jfi",
".jfif",
".jif",
".jpe",
".jpeg",
".jpg",
".png",
".psd",
".svg",
".tif",
".tiff",
".webp",
".xcf",
".ttf",
".otf",
".lock",
".css",
".less",
".admx",
".adml",
".xsd",
".nse",
".xsl",
".zip",
".tar",
".tar.gz",
".so",
".nessus",
]
triage = "gray"

[[Rule]]
scope = "File"
id = "d3"
name = "DiscardByFileName"
action = "Discard"
category = []
relay = []
description = "Skip any further scanning for files with these extensions."
matchLocation = "FilePath"
matchLength = 0
importance = ""
wordListType = "EndsWith"
wordList = [
"initrd.img",
"initrd.img.old",
"jmxremote\\.password\\.template",
"sceregvl\\.inf"
]
triage = "gray"

[[Rule]]
scope = "Content"
id = "d4"
name = "Generic file content snaffle"
action = "Snaffle"
category = []
relay = []
description = "Pick these up."
matchLocation = "FileContentAsString"
matchLength = 0
importance = "⭐"
wordListType = "Contains"
wordList = [
"password",
"passwd",
"pass",
"credential",
"cred",
"sifre",
"şifre",
]
triage = "green"

[[Rule]]
scope = "File"
id = "d5"
name = "Interesting File"
action = "Snaffle"
category = []
relay = []
description = "Pick these up."
matchLocation = "FileName"
matchLength = 0
importance = "⭐⭐"
wordListType = "Regex"
wordList = [
"\\.mozilla\\/firefox\\/.*/logins\\.json",
]
triage = "blue"

[[Rule]]
scope = "Directory"
id = "d6"
name = "PythonDiscard"
action = "Discard"
category = []
relay = []
description = "Python discard directories."
matchLocation = "FilePath"
matchLength = 0
importance = ""
wordListType = "Contains"
wordList = [
"\\/share\\/pipx",
]
triage = "gray"

[[Rule]]
scope = "Directory"
id = "d7"
name = "GoDiscard"
action = "Discard"
category = []
relay = []
description = "Go discard directories."
matchLocation = "FilePath"
matchLength = 0
importance = ""
wordListType = "Contains"
wordList = [
"\\/go\\/bin",
"\\/go\\/pkg",
"\\/go-build\\/"
]
triage = "gray"

[[Rule]]
scope = "Content"
id = "d8"
name = "KeepCertRegexRed"
action = "Snaffle"
category = []
relay = []
description = "Private keys."
matchLocation = "FileContentAsString"
importance = "⭐⭐⭐⭐⭐"
wordListType = "Regex"
matchLength = 0
wordList = ["-----BEGIN( RSA| OPENSSH| DSA| EC| PGP)? PRIVATE KEY( BLOCK)?-----"]
triage = "red"

[[Rule]]
scope = "File"
id = "d9"
name = "KeepPathContainsRed"
action = "Snaffle"
category = []
relay = []
description = "Files with a path containing these strings are very interesting."
matchLocation = "FilePath"
importance = "⭐⭐⭐⭐⭐"
wordListType = "Contains"
matchLength = 0
wordList = ["\\.purple\\/accounts.xml", 
"\\.gem\\/credentials", 
"config\\/hub"]
triage = "red"

[[Rule]]
scope = "Content"
id = "d10"
name = "KeepConfigRegexRed"
action = "Snaffle"
category = []
relay = []
description = "A description of what a rule does."
matchLocation = "FileContentAsString"
importance = "⭐⭐⭐⭐⭐"
wordListType = "Regex"
matchLength = 0
wordList = ["NVRAM config last updated", 
"enable password \\.", 
"simple-bind authenticated encrypt"]
triage = "red"

[[Rule]]
scope = "File"
id = "d11"
name = "KeepExtExactYellow"
action = "Snaffle"
category = []
relay = []
description = "Files with these extensions are a little interesting."
matchLocation = "FileExtension"
importance = "⭐⭐⭐"
wordListType = "Exact"
matchLength = 0
wordList = ["\\.key", 
"\\.keypair", 
"\\.jks", ]
triage = "yellow"

[[Rule]]
scope = "File"
id = "d12"
name = "KeepFilenameExactRed"
action = "Snaffle"
category = []
relay = []
description = "Files with these exact names are very interesting."
matchLocation = "FileName"
importance = "⭐⭐⭐⭐⭐"
wordListType = "Exact"
matchLength = 0
wordList = [
"otr\\.private_key", 
"Favorites\\.plist", 
"proxy\\.config", 
"keystore", 
"keyring", 
"\\.gitconfig", 
"\\.dockercfg", 
"key3\\.db", 
"key4\\.db", 
"Login Data"]
triage = "red"

[[Rule]]
scope = "File"
id = "d13"
name = "KeepFilenameExactYellow"
action = "Snaffle"
category = []
relay = []
description = "Files with these exact names are very interesting."
matchLocation = "FileName"
importance = "⭐⭐⭐"
wordListType = "EndsWith"
matchLength = 0
wordList = [
"web\\.config", 
]
triage = "yellow"