[[Rule]]
scope = "Directory"
name = "PerlDirectoryDiscard"
action = "Discard"
category = []
relay = []
description = "Skip any further scanning for files with these extensions."
matchLocation = "FileExtension"
matchLength = 0
importance = ""
wordListType = "Contains"
wordList = [
"\\/perl\\/man",
"\\/perl\\/lib",
]
triage = "gray"